### ISSUE TITLE
Add Twitter Reference

### ISSUE THREAD

**Issue by slstarnes** [atl-jugheads/atl-jugheads.github.io#5]
Add link for users to follow @jupyteratlanta

Below is the embed code:
<a href="https://twitter.com/jupyteratlanta?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @jupyteratlanta</a><script async src="https://platform.twitter.com/widgets.js" data-size="large" charset="utf-8"></script>

**Comment by tonyfast** [comment]
Using the badge in https://github.com/atl-jugheads/jupyter-day-atlanta-ii/blob/master/_includes/twitter_badge.html
