### ISSUE TITLE
Fix status text in Gitter

### ISSUE THREAD

**Issue by slstarnes** [atl-jugheads/atl-jugheads.github.io#6]
When using Gitter on the web, there is text at the top saing that the next event is in December. This needs to be updated.

**Comment by tonyfast** [comment]
<img width="952" alt="screen shot 2018-02-18 at 9 39 15 pm" src="https://user-images.githubusercontent.com/4236275/36360683-3861f0dc-14f4-11e8-80b0-46320fee0361.png">
